workflows:
  build_rewan_apk:
    name: Build Rewan APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-ddddf5194@gmail.com
